# -*- coding: utf-8 -*-
"""BMI calculator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CHh5t7yHfC2uThz2bTCow5VzqWQ4WyEu
"""

def calculate_bmi(weight, height):
    """Calculate BMI given weight (in kilograms) and height (in meters)"""
    bmi = weight / (height ** 2)
    return bmi

def get_bmi_category(bmi):
    """Determine BMI category given BMI value"""
    if bmi < 18.5:
        return "Underweight"
    elif bmi < 25:
        return "Normal Healthy Weight"
    elif bmi < 30:
        return "Overweight"
    elif bmi < 35:
        return "Obesity"
    else:
        return "Severe Obesity"

def main():
    # Input weight and height
    weight = float(input("Enter your weight in kilograms: "))
    height = float(input("Enter your height in meters: "))

    # Calculate BMI
    bmi = calculate_bmi(weight, height)

    # Determine BMI category
    category = get_bmi_category(bmi)

    # Print results
    print("Your BMI is:", bmi)
    print("BMI Category:", category)

if __name__ == "__main__":
    main()